apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: resource-secret
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: resource-secret
            key: password
  restartPolicy: Never
